
CREATE TABLE IF NOT EXISTS quality_rules (
    id INT AUTO_INCREMENT PRIMARY KEY,
    rule_name VARCHAR(255) UNIQUE NOT NULL COMMENT '规则名称',
    category VARCHAR(255) COMMENT '规则分类',
    scoring_standard JSON COMMENT '评分标准 (JSON格式)',
    weight DECIMAL(5, 2) DEFAULT 1.0 COMMENT '分数权重',
    is_enabled BOOLEAN DEFAULT TRUE COMMENT '启用状态',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
