CREATE TABLE IF NOT EXISTS knowledge_article_read_sessions (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    session_id VARCHAR(64) NOT NULL,
    user_id INT NOT NULL,
    department_id INT NULL,
    article_id BIGINT UNSIGNED NOT NULL,
    started_at DATETIME NOT NULL,
    ended_at DATETIME NULL,
    duration_seconds INT DEFAULT 0,
    active_seconds INT DEFAULT 0,
    scroll_depth_percent INT DEFAULT 0,
    full_read TINYINT(1) DEFAULT 0,
    close_type ENUM('user_close','auto_close','tab_hidden') DEFAULT 'user_close',
    heartbeats_count INT DEFAULT 0,
    wheel_events INT DEFAULT 0,
    mousemove_events INT DEFAULT 0,
    keydown_events INT DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uniq_session_id (session_id),
    KEY idx_article_id (article_id),
    KEY idx_user_id (user_id),
    KEY idx_started_at (started_at),
    CONSTRAINT fk_read_sessions_article FOREIGN KEY (article_id) REFERENCES knowledge_articles(id) ON DELETE CASCADE,
    CONSTRAINT fk_read_sessions_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);