-- 创建节假日配置表
CREATE TABLE IF NOT EXISTS holidays (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(20) NOT NULL COMMENT '假期名称',
  days INT NOT NULL CHECK (days >= 1 AND days <= 31) COMMENT '天数',
  month INT NOT NULL CHECK (month >= 1 AND month <= 12) COMMENT '所属月份',
  year INT NOT NULL COMMENT '年份',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_year_month (year, month)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='节假日配置表';
